### ISSUE TITLE
error in loading tsibbledata

### ISSUE THREAD

**Issue by yijunwang0805** [tidyverts/tsibbledata#15]
Hi,

Thank you for your package! 

I was trying to reproduce an example for TSLM with an exogenous regressor, but I could not load the dataset `UKLungDeaths`.

```r
> library(tsibbledata)
> UKLungDeaths
Error: object 'UKLungDeaths' not found

> UKLungDeaths %>% 
+   model(lm = TSLM(mdeaths ~ fourier("year", K = 4) + fdeaths)) %>% 
+   generate(UKLungDeaths, times = 5)
Error in eval(lhs, parent, parent) : object 'UKLungDeaths' not found
```

Does it have something to do with the Rmcd check failing?

![image](https://user-images.githubusercontent.com/56286591/91789173-aa73cf80-ec40-11ea-9703-8ba4efac3024.png)

Thank you for your work!

Yijun

**Comment by mitchelloharawild** [comment]
`UKLungDeaths` is a dataset produced from `mdeaths` and `fdeaths` which is not included in this package.
It can be produced with:
```r
UKLungDeaths <- as_tsibble(cbind(mdeaths, fdeaths), pivot_longer = FALSE)
```

**Comment by yijunwang0805** [comment]
Thank you Mitchell!
